### ISSUE TITLE
Allow to change the language used for spell check

### ISSUE THREAD

**Issue by ahoisl** [kria/CommitFormatter#12]
Not sure how the spell check chooses the language, seems to be linked to the input language.
Please, provide a way to switch the language.

Reason: You may use a different keyboard layout than the language you are typing; e.g. I use German keyboard, but write in English

**Comment by ahoisl** [comment]
Workaround: you can actually change the language by setting the OS default language to the desired language and restart Visual Studio.
(I guess this is common to WPF spell checking support, so this can be closed as by design)

**Comment by 1aam2am1** [comment]
Can this be changed to Visual Studio Language and not the OS. As I'm Polish have Polish Windows, but use and write commits in English.
