### ISSUE TITLE
Add "completion support" in the commit message editor

### ISSUE THREAD

**Issue by tiesmaster** [kria/CommitFormatter#5]
It would be really awesome if it would be possible to add "completion support" to the editor. What I mean by that, is when writing commit messages, I often add class names, type members (like methods, and properties), and such. Basically, things that would appear in the `git diff` listing. Using tab-completion makes it a lot easier to write those messages.

I have a setup like that now, by virtue of using a different editor for the commit message (it lists the entire git diff below the commit message, and the editor supports completion out of the box, just using the tabkey).

I don't know how hard it is to get to the git diff from the team explorer infrastructure as a source for completion, and additionally showing a completion list in the editor (VS might already give you the building blocks for showing a completion list, but otherwise it would be too difficult to built in WPF), but I'm willing to investigate that. Would you be willing to incorporate a feature like that?

BTW This extension is really awesome!! I was planning to make a similar extension (with support for issue ID tracking), but don't need to anymore 😄

**Comment by kria** [comment]
Sounds like a cool idea. If you can't get a diff from team explorer, libgit2sharp is always an option. I just skimmed through Microsoft.TeamFoundation.Controls.dll and `AutoCompleteManager` looks interesting.

If you get something working, I'd be happy to merge it!

**Comment by tiesmaster** [comment]
Ok, awesome, and thanks for the pointers ;) I'll have a look this weekend.

**Comment by tiesmaster** [comment]
The TeamExplorer thing [isn't going to work](http://stackoverflow.com/questions/40947660/how-to-retrieve-the-diff-patch-from-team-explorer/40948154#40948154), but using libgit2Sharp works perfectly.

I haven't figured out yet how to do completion in the editor. I couldn't find the `AutoCompleteManager` class, where you talking about the [`AutoComplete`](https://msdn.microsoft.com/en-us/libRary/microsoft.teamfoundation.controls.wpf.autocomplete%28v=vs.110%29?f=255&MSPPError=-2147217396)?

**Comment by tiesmaster** [comment]
Stale
